apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - node-alerts.yaml
  - pod-workload-alerts.yaml
  - storage-controlplane-alerts.yaml

commonLabels:
  app.kubernetes.io/part-of: k3s-monitoring
  app.kubernetes.io/managed-by: argocd
