apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robusta

resources:
  - ../../base/application.yaml

# Generate ConfigMap from values file
configMapGenerator:
  - name: robusta-values
    files:
      - values.yaml

# Patch the ArgoCD Application for prod
patches:
  - target:
      kind: Application
      name: robusta
    patch: |-
      - op: replace
        path: /metadata/name
        value: robusta-prod
      - op: add
        path: /spec/source/helm/valueFiles
        value:
          - values.yaml
      - op: replace
        path: /spec/destination/namespace
        value: robusta

commonLabels:
  environment: prod
