apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robusta

resources:
  - application.yaml
  # Uncomment after creating secrets
  # - secrets.yaml

configMapGenerator:
  - name: robusta-values
    files:
      - values.yaml

commonLabels:
  app.kubernetes.io/name: robusta
  app.kubernetes.io/part-of: monitoring-stack
