# Pod Scheduling & Image Alert Enrichment
customPlaybooks:
  - triggers:
      - on_prometheus_alert:
          alert_name: PodPending
    actions:
      - pod_events_enricher: {}
      - pod_issue_investigator: {}

  - triggers:
      - on_prometheus_alert:
          alert_name: PodSchedulingFailed
    actions:
      - pod_events_enricher: {}
      - pod_issue_investigator: {}

  - triggers:
      - on_prometheus_alert:
          alert_name: PodImagePullBackOff
    actions:
      - pod_events_enricher: {}
      - image_pull_backoff_reporter: {}
